[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = _serve_one(child_r, fds,
          File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one

      File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    code = spawn._main(child_r, parent_sentinel)    
    prepare(preparation_data)  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
code = spawn._main(child_r, parent_sentinel)

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])prepare(preparation_data)

      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
_fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
        _fixup_main_from_path(data['init_main_from_path'])main_content = runpy.run_path(main_path,

      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,main_content = runpy.run_path(main_path,
    
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
main_content = runpy.run_path(main_path,  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path

  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
      File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,    return _run_module_code(code, init_globals, run_name,
return _run_module_code(code, init_globals, run_name,

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
            _run_code(code, mod_globals, init_globals,_run_code(code, mod_globals, init_globals,_run_code(code, mod_globals, init_globals,


  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
      File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    exec(code, run_globals)        
    exec(code, run_globals)exec(code, run_globals)  File "/opt/conda/bin/fmriprep", line 5, in <module>
from fmriprep.cli.run import main


  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from fmriprep.cli.run import main
          File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
from fmriprep.cli.run import mainfrom fmriprep.cli.run import main

      File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
        from .. import configfrom .. import config

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
      File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
            from templateflow import __version__ as _tf_verfrom templateflow import __version__ as _tf_verfrom . import api

    
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
from . import api  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
        from . import api    from . import api
    
from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
        from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout        

install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
        install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
        return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    return return_func(generator_func)(*args, **kwargs)    
return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)    
results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        results = list(results)
results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(    
for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for r in _process_results(for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
        for r in destination_dataset.get(for r in destination_dataset.get(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for r in destination_dataset.get(for r in destination_dataset.get(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for r in _process_results(for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for r in _process_results(for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
        refds = require_dataset(refds = require_dataset(

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
        refds = require_dataset(refds = require_dataset(

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
        raise ValueError(u"No installed dataset found at "raise ValueError(u"No installed dataset found at "

ValueErrorValueError: : No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow.No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow.

        raise ValueError(u"No installed dataset found at "raise ValueError(u"No installed dataset found at "

ValueErrorValueError: : No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow.No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_01_wf/unwarp_wf/resample/sourcedata/templateflow.

[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
        code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,    

code = _serve_one(child_r, fds,  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one

      File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
        code = spawn._main(child_r, parent_sentinel)    code = spawn._main(child_r, parent_sentinel)
code = spawn._main(child_r, parent_sentinel)

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
            prepare(preparation_data)prepare(preparation_data)prepare(preparation_data)

    
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
prepare(preparation_data)  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
            _fixup_main_from_path(data['init_main_from_path'])_fixup_main_from_path(data['init_main_from_path'])_fixup_main_from_path(data['init_main_from_path'])    


_fixup_main_from_path(data['init_main_from_path'])  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
        main_content = runpy.run_path(main_path,main_content = runpy.run_path(main_path,

  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
        main_content = runpy.run_path(main_path,main_content = runpy.run_path(main_path,

  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
        return _run_module_code(code, init_globals, run_name,return _run_module_code(code, init_globals, run_name,

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
        return _run_module_code(code, init_globals, run_name,return _run_module_code(code, init_globals, run_name,

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,_run_code(code, mod_globals, init_globals,

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
        _run_code(code, mod_globals, init_globals,_run_code(code, mod_globals, init_globals,

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)exec(code, run_globals)

  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
        exec(code, run_globals)exec(code, run_globals)

  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
        from fmriprep.cli.run import mainfrom fmriprep.cli.run import main

          File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
from fmriprep.cli.run import mainfrom fmriprep.cli.run import main

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
        from .. import configfrom .. import config        

from .. import configfrom .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
                from templateflow import __version__ as _tf_verfrom templateflow import __version__ as _tf_verfrom templateflow import __version__ as _tf_verfrom templateflow import __version__ as _tf_ver



  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
                from . import apifrom . import apifrom . import apifrom . import api



  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
                from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout



  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
                install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
                return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
                results = list(results)results = list(results)results = list(results)results = list(results)



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
                for r in _process_results(for r in _process_results(for r in _process_results(for r in _process_results(



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
                for res in results:for res in results:for res in results:for res in results:



  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
                for r in res:for r in res:for r in res:for r in res:



  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
            for r in _process_results(    for r in _process_results(for r in _process_results(
for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
            for res in results:for res in results:    for res in results:

for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__

  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__
            yield from clone_dataset(yield from clone_dataset(yield from clone_dataset(
    

  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset
yield from clone_dataset(  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset

  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset
        GitRepo.clone(GitRepo.clone(    

GitRepo.clone(
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 949, in clone
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 949, in clone
      File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 949, in clone
GitRepo.clone(
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 949, in clone
            raise ValueError(raise ValueError(raise ValueError(


    ValueErrorValueErrorValueErrorraise ValueError(: : : 
destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.ValueError


: destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_02_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset
    GitRepo.clone(
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 994, in clone
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset
    res = GitWitlessRunner().run(
  File "/opt/conda/lib/python3.8/site-packages/datalad/runner/runner.py", line 145, in run
    raise CommandError(
datalad.runner.exception.CommandError    : GitRepo.clone(
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 994, in clone
CommandError: 'git -c diff.ignoreSubmodules=none clone --progress https://github.com/templateflow/templateflow.git /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow' failed with exitcode 128 [err: 'fatal: destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 589, in clone_dataset
    code = _serve_one(child_r, fds,
[INFO] Completed clone attempts for Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow) 
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    res = GitWitlessRunner().run(
  File "/opt/conda/lib/python3.8/site-packages/datalad/runner/runner.py", line 145, in run
    GitRepo.clone(        
raise CommandError(code = spawn._main(child_r, parent_sentinel)

  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 994, in clone
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
datalad.runner.exception.CommandError:     prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
CommandError: 'git -c diff.ignoreSubmodules=none clone --progress https://github.com/templateflow/templateflow.git /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow' failed with exitcode 128 [err: 'fatal: destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
        code = _serve_one(child_r, fds,res = GitWitlessRunner().run(

  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/site-packages/datalad/runner/runner.py", line 145, in run
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    raise CommandError(
    code = spawn._main(child_r, parent_sentinel)datalad.runner.exception
.CommandError  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
:     prepare(preparation_data)
CommandError: 'git -c diff.ignoreSubmodules=none clone --progress https://github.com/templateflow/templateflow.git /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow' failed with exitcode 128 [err: 'fatal: destination path '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow' already exists and is not an empty directory.']
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare

During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
_run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    _fixup_main_from_path(data['init_main_from_path'])    
exec(code, run_globals)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    code = _serve_one(child_r, fds,
      File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
        from .. import configcode = spawn._main(child_r, parent_sentinel)

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)    
return _run_module_code(code, init_globals, run_name,      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare

from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
        from . import api    _run_code(code, mod_globals, init_globals,
_fixup_main_from_path(data['init_main_from_path'])

  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout    
exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    main_content = runpy.run_path(main_path,
      File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    from fmriprep.cli.run import maininstall(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    from .. import config    
return _run_module_code(code, init_globals, run_name,  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    exec(code, run_globals)
      File "/opt/conda/bin/fmriprep", line 5, in <module>
from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from fmriprep.cli.run import main
      File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutresults = list(results)

  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    from .. import config
      File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
        from . import api
return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
        for res in results:from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)for r in res:

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
    for res in results:
      File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__
results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in res:
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    yield from clone_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 609, in clone_dataset
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    rmtree(str(dest_path), children_only=dest_path_existed)
      File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 471, in rmtree
for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 365, in __call__
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__
        rotree(path, ro=False, chmod_files=chmod_files)for r in res:

  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 435, in rotree
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    yield from clone_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 609, in clone_dataset
        for r in _process_results(chmod(root)

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 426, in <lambda>
    rmtree(str(dest_path), children_only=dest_path_existed)
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 471, in rmtree
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
    chmod = lambda f: os.chmod(f, os.stat(f).st_mode | stat.S_IWRITE | stat.S_IREAD)
FileNotFoundError    for res in results:
:   File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 320, in __call__
[Errno 2] No such file or directory: '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow/.git/hooks'
    rotree(path, ro=False, chmod_files=chmod_files)
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 435, in rotree
    yield from clone_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/distributed/clone.py", line 609, in clone_dataset
    chmod(root)
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 426, in <lambda>
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
    rmtree(str(dest_path), children_only=dest_path_existed)
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 471, in rmtree
    chmod = lambda f: os.chmod(f, os.stat(f).st_mode | stat.S_IWRITE | stat.S_IREAD)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow/.git'
    rotree(path, ro=False, chmod_files=chmod_files)
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 435, in rotree
    chmod(root)
  File "/opt/conda/lib/python3.8/site-packages/datalad/utils.py", line 426, in <lambda>
    chmod = lambda f: os.chmod(f, os.stat(f).st_mode | stat.S_IWRITE | stat.S_IREAD)
FileNotFoundError: [INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow 
[Errno 2] No such file or directory: '/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow/.git'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_03_wf/unwarp_wf/resample/sourcedata/templateflow.
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Completed clone attempts for Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow) 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_04_wf/unwarp_wf/resample/sourcedata/templateflow.
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Completed clone attempts for Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow) 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow 
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_05_wf/unwarp_wf/resample/sourcedata/templateflow.
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
Traceback (most recent call last):
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    prepare(preparation_data)    
_run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
      File "/opt/conda/bin/fmriprep", line 5, in <module>
_fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    main_content = runpy.run_path(main_path,    
from .. import config
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
        return _run_module_code(code, init_globals, run_name,from templateflow import __version__ as _tf_ver

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api    
_run_code(code, mod_globals, init_globals,  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
      File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
        install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
        return return_func(generator_func)(*args, **kwargs)from .. import config

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
      File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow.
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
        return _run_module_code(code, init_globals, run_name,_fixup_main_from_path(data['init_main_from_path'])

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
      File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    from .. import config
    _run_code(code, mod_globals, init_globals,  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)    
from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for res in results:for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    refds = require_dataset(    
raise ValueError(u"No installed dataset found at "
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow.
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_06_wf/unwarp_wf/resample/sourcedata/templateflow.
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
        code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,

  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
        code = spawn._main(child_r, parent_sentinel)
code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
        return _run_module_code(code, init_globals, run_name,
_run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
        _run_code(code, mod_globals, init_globals,exec(code, run_globals)

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main    
exec(code, run_globals)  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>

  File "/opt/conda/bin/fmriprep", line 5, in <module>
        from fmriprep.cli.run import mainfrom .. import config

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
        from . import api
from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
        from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom . import api

  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
        from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(    
for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for r in _process_results(for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
        refds = require_dataset(refds = require_dataset(

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
        raise ValueError(u"No installed dataset found at "raise ValueError(u"No installed dataset found at "

ValueErrorValueError: : No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow.No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_07_wf/unwarp_wf/resample/sourcedata/templateflow.

[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
Traceback (most recent call last):
        code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main


  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
        code = spawn._main(child_r, parent_sentinel)code = spawn._main(child_r, parent_sentinel)

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
            code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,code = _serve_one(child_r, fds,


  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
            prepare(preparation_data)prepare(preparation_data)code = _serve_one(child_r, fds,


  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
            code = spawn._main(child_r, parent_sentinel)    code = spawn._main(child_r, parent_sentinel)code = spawn._main(child_r, parent_sentinel)

_fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
code = spawn._main(child_r, parent_sentinel)        
    prepare(preparation_data)prepare(preparation_data)prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main


      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,    
prepare(preparation_data)  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path

          File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])_fixup_main_from_path(data['init_main_from_path'])
_fixup_main_from_path(data['init_main_from_path'])

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
        _fixup_main_from_path(data['init_main_from_path'])
return _run_module_code(code, init_globals, run_name,    
      File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,      File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
main_content = runpy.run_path(main_path,main_content = runpy.run_path(main_path,
_run_code(code, mod_globals, init_globals,


  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    _run_code(code, mod_globals, init_globals,    
main_content = runpy.run_path(main_path,  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code

      File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
            return _run_module_code(code, init_globals, run_name,    return _run_module_code(code, init_globals, run_name,return _run_module_code(code, init_globals, run_name,
exec(code, run_globals)

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code

      File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/opt/conda/bin/fmriprep", line 5, in <module>
from fmriprep.cli.run import main
      File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
return _run_module_code(code, init_globals, run_name,
          File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
from fmriprep.cli.run import main        _run_code(code, mod_globals, init_globals,
_run_code(code, mod_globals, init_globals,_run_code(code, mod_globals, init_globals,
      File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
from .. import config_run_code(code, mod_globals, init_globals,  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code


  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
        from .. import configexec(code, run_globals)
        
exec(code, run_globals)  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
exec(code, run_globals)

  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
  File "/opt/conda/bin/fmriprep", line 5, in <module>
        from templateflow import __version__ as _tf_ver    from fmriprep.cli.run import main
        from fmriprep.cli.run import main
from fmriprep.cli.run import main  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
from fmriprep.cli.run import main

      File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
from templateflow import __version__ as _tf_ver  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>

      File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
            from .. import configfrom .. import config    from .. import config    

from .. import config    
from . import api
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
      File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)        
from templateflow import __version__ as _tf_ver    from templateflow import __version__ as _tf_ver
      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func

from templateflow import __version__ as _tf_ver  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
from templateflow import __version__ as _tf_ver
    
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    from . import api        
from . import apifrom . import api    

  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
from . import api  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
        from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout

      File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
return return_func(generator_func)(*args, **kwargs)        
from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layoutfrom .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func

      File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
          File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
return return_func(generator_func)(*args, **kwargs)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)


  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)    
install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    results = list(results)
          File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    return return_func(generator_func)(*args, **kwargs)return return_func(generator_func)(*args, **kwargs)

      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        results = list(results)results = list(results)

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    results = list(results)results = list(results)

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for res in results:
          File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
for r in _process_results(for r in _process_results(

          File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
for r in _process_results(for r in _process_results(    

for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in _process_results(
          File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:for r in _process_results(for res in results:


  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
        for r in destination_dataset.get(for r in destination_dataset.get(

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
        for res in results:for r in destination_dataset.get(    

for r in destination_dataset.get(      File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__

  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
for res in results:          File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func

for r in _process_results(for r in _process_results(

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(    
for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
        for res in results:for res in results:

      File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
        for res in results:for res in results:

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    raise ValueError(u"No installed dataset found at "
    ValueError        : raise ValueError(u"No installed dataset found at "refds = require_dataset(refds = require_dataset(


No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow.ValueError  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow.        
refds = require_dataset(refds = require_dataset(

  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
        raise ValueError(u"No installed dataset found at "raise ValueError(u"No installed dataset found at "

ValueErrorValueError: : No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow.No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow.

        raise ValueError(u"No installed dataset found at "raise ValueError(u"No installed dataset found at "

ValueErrorValueError: : No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow.No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_08_wf/unwarp_wf/resample/sourcedata/templateflow.

[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git/.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Completed clone attempts for Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow) 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000117_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ses_mri_task_facerecognition_run_09_wf/unwarp_wf/resample/sourcedata/templateflow.
